import React from 'react'

const Data =[{
    id:1,
    img :"../img/download.jpg",
        imgName:"Example Image",
        title:"Apple",
        price:" 350",
        description:"",},
        {
            id:2,
            img :"../img/download (1).jpg",
            imgName:"Example Image",
            title:"Banana",
            price:" 100",
            description:"",    
        },
        {
            id:3,
            img :"../img/download (2).jpg",
            imgName:"Example Image",
            title:"Grapes",
            price:" 300",
            description:"",    
        },
        {  id:4,
            img :"../img/download (3).jpg",
            imgName:"Example Image",
            title:"Mango",
            price:" 150",
            description:"",    
        },
        {  id:5,
            img :"../img/download (4).jpg",
            imgName:"Example Image",
            title:"pineapple",
            price:" 200",
            description:"",    
        },
        {  id:6,
            img :"../img/download (5).jpg",
            imgName:"Example Image",
            title:" papaya",
            price:" 130",
            description:"",    
        },
        {  id:7,
            img :"../img/download (6).jpg",
            imgName:"Example Image",
            title:"watermelon",
            price:" 250",
            description:"",    
        }
        ,
        {  id:8,
            img :"../img/Avocados.jpg",
            imgName:"Example Image",
            title:"Avocados",
            price:" 350",
            description:"",    
        },
        {  id:9,
            img :"../img/Dragonfruit.jpg",
            imgName:"Example Image",
            title:"Dragonfruit",
            price:" 450",
            description:"",    
        }
]
 

export default Data